application: poets
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  script: app.application

- url: /data
  static_dir: data

- url: /lib
  static_dir: lib

- url: /js
  static_dir: js

- url: /static/css
  static_dir: static/css